name=bread-crumbs-contracts
version=0.4.4
author=Cameron K. Brooks
maintainer=Cameron K. Brooks <cambrooks3393@gmail.com>
description=Header-only CRUMBS operation contracts for BREADS-compatible Slices
category=Communication
url=https://github.com/feastorg/bread-crumbs-contracts
architectures=*
depends=CRUMBS
includes=bread/bread_ops.h
